apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.form: |
    url: https://fca8-2a0d-6fc2-66d2-e000-1df8-ff2d-39f6-bda6.eu.ngrok.io
  template.form-data: |
    webhook:
      form:
        method: POST
        path: /event/argocd
        body: |
          {
            "test": "pasha"
          }