apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prom
  name: traefik
  namespace: kube-systemasd
spec:
  endpoints:
    - interval: 6s
      targetPort: 9100
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: "traefik"
